DROP TABLE SHOPPING_LIST_ITEMS;


CREATE TABLE SHOPPING_LIST_ITEMS (
    ITEM_NAME VARCHAR(256) NOT NULL UNIQUE,
    MESSAGE_ID VARCHAR(64) NOT NULL PRIMARY KEY,
    SENDER_ID VARCHAR(64) NOT NULL,
    BUYER_ID VARCHAR(64),
    SUBMITTED_AT TIMESTAMP NOT NULL,
    BOUGHT_AT TIMESTAMP,
    BOUGHT BOOLEAN DEFAULT FALSE
);

alter table SHOPPING_LIST_ITEMS drop constraint item_name;